### PR TITLE
Upgrade checkstyle to 8.25 and fix upgrade script

### PR DESCRIPTION
**Pull request by butterflysky**
One of the projects I manage with CodeClimate uses a checkstyle configuration that's incompatible with versions <8.24. I just tried to enable CodeClimate's Checkstyle plugin and found it didn't work with my configuration, so I went to upgrade the support.

This diff fixes the upgrade script to find the latest version of checkstyle's jar file (moved from sourceforge to github). It also applies the upgrade and fixes up a few things in the default configuration that are no longer compatible with versions of Checkstyle >=8.24. Now all the tests pass cleanly.

### CODE REVIEW

**Comment by efueger** [comment]
Hi @butterflysky - thanks for the PR 👌 Putting this in the queue for review.

**Comment by efueger** [comment]
Hi @butterflysky - quick update: we'll need to first upgrade this repo to use Circle 2 before merging this.

- it's on the books!

**Comment by Cludch** [comment]
May I ask if there is an ETA for the circle 2 update?
Can one help with the update?
I am also waiting for this MR.

**Comment by efueger** [comment]
Hi Jannis,

Checking with the team and will let you know.

**Comment by Cludch** [comment]
Hey,

thanks for your support. Is there an update already?

**Comment by butterflysky** [comment]
Hi @efueger; thanks for your help so far! Just checking in to see if this is still blocked.

**Comment by efueger** [comment]
Hi @butterflysky - thanks so much for your patience and the nudge! We have work scheduled in an upcoming sprint for these updates.

I'll be in touch as soon as I see any updates. 👌

**Comment by butterflysky** [comment]
Thank you @efueger , have a great day, and I'll continue to be patient. :)

**Comment by efueger** [comment]
Hi @butterflysky -

Good news! We've updated our Circle setup and are now using Checkstyle [8.26](https://github.com/codeclimate/codeclimate-checkstyle/blob/master/bin/install-checkstyle.sh#L4)

Thanks again for the nudge 👌

**Comment by butterflysky** [comment]
Thanks y'all! Have a great week!

**Pull request merged**
